# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/snorkel-tutorial',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/snorkel-tutorial',
                'lib_path': 'snorkel_tutorial'},
  'syms': {'snorkel_tutorial.core': {'snorkel_tutorial.core.foo': ('core.html#foo', 'snorkel_tutorial/core.py')}}}